### ISSUE TITLE
Show Exceptions in Bridge Console

### ISSUE THREAD

**Issue by AndreyChechel** [deckdotnet/Deck.NET#15]
Bridge Console brings a lot of value for testing your code in Deck.NET. It allows to reduce number of actions when one is debugging or demonstration her code. However, if there is a script error, the console won't appear. This forces users to switch to their debugger tool to understand what has happened.

So my idea is about wrapping executing code with a global `try-catch` statement. This will allow to show the error message in Console and probably save time for users. When an exception is logged, it should be rethrown to keep it processed by the browser, as usual.

The suggested wrapper:
```javascript
try
{
    // Deck.NET user code will be executed here
}
catch (e)
{
    Bridge.Console.error(e.message);
    throw e;
}
```

It'd be nice if Bridge Console shows Error messages in red colour.

**Comment by geoffreymcgill** [comment]
Yes, agreed. Something similar to this has been on my list for a while. 

There's a series of improvements that need to be implemented on **Bridge.Console** and the **System.Console** class. 

An Error method already exists in Bridge.Console, so we would likely use that to render an Error or Exception message thrown from native js. 

http://deck.net/c93c94ccd491bc2ae1f307cfd8ebfd3d

```cs
public class Program
{
    public static void Main()
    {
        Bridge.Utils.Console.Error("Exception");
    }
}
```

**Comment by AndreyChechel** [comment]
That's nice, I've updated my example.

**Comment by geoffreymcgill** [comment]
If Bridge Console is available, JavaScript Exceptions and Errors are now trapped and rendered to the console output. 

This functionality has been added to Bridge 16.0.0-beta.
