### ISSUE TITLE
C#7 sample: "System.Exception: TypeError: Add is not a function"

### ISSUE THREAD

**Issue by DaniilVeriga** [deckdotnet/Deck.NET#26]
https://deck.net/csharp7

Chrome

![exception](https://user-images.githubusercontent.com/1510884/41094084-b40f79be-6a55-11e8-96f4-ad9c2fc3edb4.png)

**Comment by geoffreymcgill** [comment]
Hi @DaniilVeriga Thanks for submitting this issue. Looks like this runtime error is covered by https://github.com/bridgedotnet/Bridge/issues/3625 and will be fixed in the next public release of Bridge.
