### ISSUE TITLE
Support different Bridge.net versions

### ISSUE THREAD

**Issue by emumanu** [deckdotnet/Deck.NET#29]
It would be nice to be able to choose different bridge.net versions when running the sample on deck.net.

**Comment by fabriciomurta** [comment]
Thanks for the suggestion, @emumanu!

Not to take entirely out your hopes, part of the decision in keeping just a single version was for simplicity between releases; but maybe the strongest part was, to ensure people rely on Bridge latest version with latest bugfixes. We do keep a dev.deck.net we update with the latest merges as the code evolves.

**Comment by emumanu** [comment]
@fabriciomurta I'm OK with it. 

It was laziness on my side in order to see if the generated code on the version of bridge I was using was changing on the newest ones. But as you have a lot of tests cases, getting the latest version should be a must. So I prefer you guys to spend your valuable time improving bridge instead.
