### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by TCrosmanDSI** [deckdotnet/Deck.NET#35]
Can Deck.NET convert typescript data (classes, interfaces, modules, etc) to C# classes?

I don't want a converter, I want to take existing typescript libraries and convert them to C#.  Not C# to typescript.

**Comment by fabriciomurta** [comment]
No, Deck.NET is simply a web "fiddle" interface for Bridge.NET. So it is only capable of converting C# to JavaScript. The TypeScript version it outputs (like javascript) depends on Bridge context, `bridge.js` / `bridge.d.ts`. The opposite path is not supported by Bridge at all.

I will close this believing this answers your question, if not, feel free to reply/reopen it.
