### ISSUE TITLE
Use window.onbeforeunload to prevent accidental navigation away while editing 

### ISSUE THREAD

**Issue by mcintyre321** [deckdotnet/Deck.NET#9]
Very cool site indeed!

I accidentally navigated away while editing a script, and had to use the back button to avoid losing my work. It would be great to use window.onbeforeunload to prevent this.

Also ability to save scripts would be great too :)

Keep up the good work!

**Comment by geoffreymcgill** [comment]
Yes, agreed about the `onbeforeunload` feature. We will implement this right away. 

The **Save** functionality will be implemented in a future release.

**Comment by ozguruysal** [comment]
Thanks for your feedback. This feature is now added and went [live](http://deck.net/). Please feel free to report here if you see any issues.
